services:
  postgres:
    image: postgres:16
    container_name: painel-postgres
    environment:
      POSTGRES_DB: painel_cliente
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "607733%"
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d painel_cliente"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:latest
    container_name: painel-minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  minio-init:
    image: minio/mc:latest
    container_name: painel-minio-init
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 3;
      mc alias set local http://minio:9000 minioadmin minioadmin123;
      mc mb -p local/painel-docs || true;
      exit 0;
      "

volumes:
  postgres_data:
  minio_data:
